"""baseline current schema

Revision ID: 0001
Revises:
Create Date: 2026-08-25 12:10:35.004362

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel



revision: str = '0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ephemeral',
    sa.Column('ns', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('k', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('v', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('ns', 'k')
    )
    op.create_index(op.f('ix_ephemeral_expires_at'), 'ephemeral', ['expires_at'], unique=False)
    op.create_table('oauthclient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uris', sa.JSON(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('refreshed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', name='uq_oauth_client_id')
    )
    op.create_index(op.f('ix_oauthclient_client_id'), 'oauthclient', ['client_id'], unique=False)
    op.create_table('org',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('public_demo', sa.Boolean(), nullable=False),
    sa.Column('balance_micro', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stripe_default_pm', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('autotopup_enabled', sa.Boolean(), nullable=False),
    sa.Column('autotopup_threshold_micro', sa.Integer(), nullable=False),
    sa.Column('autotopup_amount_micro', sa.Integer(), nullable=False),
    sa.Column('autotopup_monthly_cap_micro', sa.Integer(), nullable=False),
    sa.Column('autotopup_consented_at', sa.DateTime(), nullable=True),
    sa.Column('autotopup_disabled_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('autotopup_last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('autotopup_failures', sa.Integer(), nullable=False),
    sa.Column('autotopup_recovery_pi', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('budget_dims', sa.JSON(), nullable=True),
    sa.Column('primary_dim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('daily_cap_micro', sa.Integer(), nullable=False),
    sa.Column('ad_gclid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ad_click_id_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ad_click_at', sa.DateTime(), nullable=True),
    sa.Column('ad_landing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_medium', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_campaign', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_term', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_content', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('utm_referrer', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_call_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_org_slug'), 'org', ['slug'], unique=True)
    op.create_index(op.f('ix_org_stripe_customer_id'), 'org', ['stripe_customer_id'], unique=False)
    op.create_table('searchmiss',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchmiss_created_at'), 'searchmiss', ['created_at'], unique=False)
    op.create_index(op.f('ix_searchmiss_source'), 'searchmiss', ['source'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('suspended', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('demo', sa.Boolean(), nullable=False),
    sa.Column('referral_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_referral_code'), 'user', ['referral_code'], unique=True)
    op.create_table('adconversion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_usd_micro', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'action', name='uq_adconversion_org_action')
    )
    op.create_index(op.f('ix_adconversion_failed_at'), 'adconversion', ['failed_at'], unique=False)
    op.create_index(op.f('ix_adconversion_next_attempt_at'), 'adconversion', ['next_attempt_at'], unique=False)
    op.create_index(op.f('ix_adconversion_org_id'), 'adconversion', ['org_id'], unique=False)
    op.create_index(op.f('ix_adconversion_uploaded_at'), 'adconversion', ['uploaded_at'], unique=False)
    op.create_table('bundle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recipe', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('files', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bundle_name'), 'bundle', ['name'], unique=False)
    op.create_index(op.f('ix_bundle_org_id'), 'bundle', ['org_id'], unique=False)
    op.create_index(op.f('ix_bundle_owner'), 'bundle', ['owner'], unique=False)
    op.create_table('callrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credential_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cost_estimated_micro', sa.Integer(), nullable=True),
    sa.Column('cost_observed_micro', sa.Integer(), nullable=True),
    sa.Column('cost_charged_micro', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('response_bytes', sa.Integer(), nullable=True),
    sa.Column('params_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_request', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('refused_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('call_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_dim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('budget_val', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_callrecord_budget_val'), 'callrecord', ['budget_val'], unique=False)
    op.create_index(op.f('ix_callrecord_call_ref'), 'callrecord', ['call_ref'], unique=False)
    op.create_index(op.f('ix_callrecord_client'), 'callrecord', ['client'], unique=False)
    op.create_index(op.f('ix_callrecord_endpoint_id'), 'callrecord', ['endpoint_id'], unique=False)
    op.create_index(op.f('ix_callrecord_org_id'), 'callrecord', ['org_id'], unique=False)
    op.create_index(op.f('ix_callrecord_params_hash'), 'callrecord', ['params_hash'], unique=False)
    op.create_index(op.f('ix_callrecord_provider'), 'callrecord', ['provider'], unique=False)
    op.create_index(op.f('ix_callrecord_refused_by'), 'callrecord', ['refused_by'], unique=False)
    op.create_index(op.f('ix_callrecord_tool_name'), 'callrecord', ['tool_name'], unique=False)
    op.create_index(op.f('ix_callrecord_user_email'), 'callrecord', ['user_email'], unique=False)
    op.create_table('capabilitypin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('capability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'capability', name='uq_pin_org_capability')
    )
    op.create_index(op.f('ix_capabilitypin_capability'), 'capabilitypin', ['capability'], unique=False)
    op.create_index(op.f('ix_capabilitypin_org_id'), 'capabilitypin', ['org_id'], unique=False)
    op.create_table('creditblock',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_micro', sa.Integer(), nullable=False),
    sa.Column('remaining_micro', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_payment_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creditblock_kind'), 'creditblock', ['kind'], unique=False)
    op.create_index(op.f('ix_creditblock_org_id'), 'creditblock', ['org_id'], unique=False)
    op.create_index(op.f('ix_creditblock_stripe_payment_intent'), 'creditblock', ['stripe_payment_intent'], unique=True)
    op.create_table('hold',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_micro', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hold_created_at'), 'hold', ['created_at'], unique=False)
    op.create_index(op.f('ix_hold_org_id'), 'hold', ['org_id'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('tool_access', sa.JSON(), nullable=True),
    sa.Column('project_access', sa.JSON(), nullable=True),
    sa.Column('local_run_enabled', sa.Boolean(), nullable=False),
    sa.Column('landing', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_code_hash'), 'invite', ['code_hash'], unique=False)
    op.create_index(op.f('ix_invite_email'), 'invite', ['email'], unique=False)
    op.create_index(op.f('ix_invite_email_token_hash'), 'invite', ['email_token_hash'], unique=False)
    op.create_index(op.f('ix_invite_org_id'), 'invite', ['org_id'], unique=False)
    op.create_table('ledgerentry',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount_micro', sa.Integer(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledgerentry_block_id'), 'ledgerentry', ['block_id'], unique=False)
    op.create_index(op.f('ix_ledgerentry_call_id'), 'ledgerentry', ['call_id'], unique=False)
    op.create_index(op.f('ix_ledgerentry_created_at'), 'ledgerentry', ['created_at'], unique=False)
    op.create_index(op.f('ix_ledgerentry_kind'), 'ledgerentry', ['kind'], unique=False)
    op.create_index(op.f('ix_ledgerentry_org_id'), 'ledgerentry', ['org_id'], unique=False)
    op.create_table('membership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('promoted_from', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('daily_call_cap', sa.Integer(), nullable=False),
    sa.Column('tool_access', sa.JSON(), nullable=True),
    sa.Column('project_access', sa.JSON(), nullable=True),
    sa.Column('local_run_enabled', sa.Boolean(), nullable=False),
    sa.Column('pinned_tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'org_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_membership_org_id'), 'membership', ['org_id'], unique=False)
    op.create_index(op.f('ix_membership_token_hash'), 'membership', ['token_hash'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.create_table('oauthcode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_challenge', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_oauth_code')
    )
    op.create_index(op.f('ix_oauthcode_client_id'), 'oauthcode', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauthcode_code'), 'oauthcode', ['code'], unique=False)
    op.create_index(op.f('ix_oauthcode_org_id'), 'oauthcode', ['org_id'], unique=False)
    op.create_index(op.f('ix_oauthcode_user_id'), 'oauthcode', ['user_id'], unique=False)
    op.create_table('oauthgrant',
    sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_org_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['current_org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('family_id')
    )
    op.create_index(op.f('ix_oauthgrant_current_org_id'), 'oauthgrant', ['current_org_id'], unique=False)
    op.create_table('oauthrefresh',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('family_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('retired_at', sa.DateTime(), nullable=True),
    sa.Column('retired_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_oauth_refresh_token')
    )
    op.create_index(op.f('ix_oauthrefresh_client_id'), 'oauthrefresh', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauthrefresh_family_id'), 'oauthrefresh', ['family_id'], unique=False)
    op.create_index(op.f('ix_oauthrefresh_org_id'), 'oauthrefresh', ['org_id'], unique=False)
    op.create_index(op.f('ix_oauthrefresh_token_hash'), 'oauthrefresh', ['token_hash'], unique=False)
    op.create_index(op.f('ix_oauthrefresh_user_id'), 'oauthrefresh', ['user_id'], unique=False)
    op.create_table('pendingoauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('redirect_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code_verifier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auth_params', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_endpoint_auth_method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('client_id_param', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_separator', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('long_lived_exchange', sa.Boolean(), nullable=False),
    sa.Column('replaces_secret_id', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secret_id', sa.Integer(), nullable=True),
    sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pendingoauth_org_id'), 'pendingoauth', ['org_id'], unique=False)
    op.create_index(op.f('ix_pendingoauth_owner'), 'pendingoauth', ['owner'], unique=False)
    op.create_index(op.f('ix_pendingoauth_state'), 'pendingoauth', ['state'], unique=True)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'slug', name='uq_project_org_slug')
    )
    op.create_index(op.f('ix_project_org_id'), 'project', ['org_id'], unique=False)
    op.create_index(op.f('ix_project_slug'), 'project', ['slug'], unique=False)
    op.create_table('referral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('referrer_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_user_id', sa.Integer(), nullable=False),
    sa.Column('referred_org_id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reject_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qualifying_payment_intent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('card_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referrer_block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referred_block_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('referrer_reward_micro', sa.Integer(), nullable=False),
    sa.Column('referred_reward_micro', sa.Integer(), nullable=False),
    sa.Column('qualified_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['referrer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qualifying_payment_intent', name='uq_referral_qualifying_pi'),
    sa.UniqueConstraint('referred_org_id', name='uq_referral_referred_org')
    )
    op.create_index(op.f('ix_referral_card_fingerprint'), 'referral', ['card_fingerprint'], unique=False)
    op.create_index(op.f('ix_referral_code'), 'referral', ['code'], unique=False)
    op.create_index(op.f('ix_referral_created_at'), 'referral', ['created_at'], unique=False)
    op.create_index(op.f('ix_referral_referred_user_id'), 'referral', ['referred_user_id'], unique=False)
    op.create_index(op.f('ix_referral_referrer_user_id'), 'referral', ['referrer_user_id'], unique=False)
    op.create_index(op.f('ix_referral_status'), 'referral', ['status'], unique=False)
    op.create_index('ix_referral_status_qualified', 'referral', ['status', 'qualified_at'], unique=False)
    op.create_table('runrecord',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bundle_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('argv', sa.JSON(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runrecord_bundle_name'), 'runrecord', ['bundle_name'], unique=False)
    op.create_index(op.f('ix_runrecord_org_id'), 'runrecord', ['org_id'], unique=False)
    op.create_index(op.f('ix_runrecord_user_email'), 'runrecord', ['user_email'], unique=False)
    op.create_table('tagbudget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('dim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('val', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('daily_cap_micro', sa.Integer(), nullable=True),
    sa.Column('monthly_cap_micro', sa.Integer(), nullable=True),
    sa.Column('calls_per_day', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'dim', 'val', name='uq_tagbudget_org_dim_val')
    )
    op.create_index(op.f('ix_tagbudget_org_id'), 'tagbudget', ['org_id'], unique=False)
    op.create_table('tagspend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('dim', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('val', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hold_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('settled', sa.Boolean(), nullable=False),
    sa.Column('amount_micro', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tagspend_created_at'), 'tagspend', ['created_at'], unique=False)
    op.create_index(op.f('ix_tagspend_hold_id'), 'tagspend', ['hold_id'], unique=False)
    op.create_index('ix_tagspend_org_dim_val_created', 'tagspend', ['org_id', 'dim', 'val', 'created_at'], unique=False)
    op.create_index(op.f('ix_tagspend_org_id'), 'tagspend', ['org_id'], unique=False)
    op.create_table('toolrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('capability', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toolrequest_capability'), 'toolrequest', ['capability'], unique=False)
    op.create_index(op.f('ix_toolrequest_created_at'), 'toolrequest', ['created_at'], unique=False)
    op.create_index(op.f('ix_toolrequest_org_id'), 'toolrequest', ['org_id'], unique=False)
    op.create_index(op.f('ix_toolrequest_source'), 'toolrequest', ['source'], unique=False)
    op.create_index(op.f('ix_toolrequest_status'), 'toolrequest', ['status'], unique=False)
    op.create_table('denyrule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('verdict', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_denyrule_org_id'), 'denyrule', ['org_id'], unique=False)
    op.create_index(op.f('ix_denyrule_project_id'), 'denyrule', ['project_id'], unique=False)
    op.create_index(op.f('ix_denyrule_user_id'), 'denyrule', ['user_id'], unique=False)
    op.create_table('idempotentcall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('membership_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('request_fingerprint', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('endpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.LargeBinary(), nullable=True),
    sa.Column('response_media_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('charged_micro', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['membership.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'key', name='uq_idem_caller_key')
    )
    op.create_index(op.f('ix_idempotentcall_key'), 'idempotentcall', ['key'], unique=False)
    op.create_index(op.f('ix_idempotentcall_membership_id'), 'idempotentcall', ['membership_id'], unique=False)
    op.create_index(op.f('ix_idempotentcall_org_id'), 'idempotentcall', ['org_id'], unique=False)
    op.create_table('secret',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('health_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('health_checked_at', sa.DateTime(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('granted_scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_ref', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_bundle_id'), 'secret', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_secret_name'), 'secret', ['name'], unique=False)
    op.create_index(op.f('ix_secret_org_id'), 'secret', ['org_id'], unique=False)
    op.create_index(op.f('ix_secret_owner'), 'secret', ['owner'], unique=False)
    op.create_index(op.f('ix_secret_provider'), 'secret', ['provider'], unique=False)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bindings', sa.JSON(), nullable=True),
    sa.Column('examples', sa.JSON(), nullable=True),
    sa.Column('health_check', sa.JSON(), nullable=True),
    sa.Column('cli', sa.JSON(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundle.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['org.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_tool_org_name')
    )
    op.create_index(op.f('ix_tool_bundle_id'), 'tool', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_tool_host'), 'tool', ['host'], unique=False)
    op.create_index(op.f('ix_tool_name'), 'tool', ['name'], unique=False)
    op.create_index(op.f('ix_tool_org_id'), 'tool', ['org_id'], unique=False)
    op.create_index(op.f('ix_tool_owner'), 'tool', ['owner'], unique=False)
    op.create_index(op.f('ix_tool_project_id'), 'tool', ['project_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_project_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_owner'), table_name='tool')
    op.drop_index(op.f('ix_tool_org_id'), table_name='tool')
    op.drop_index(op.f('ix_tool_name'), table_name='tool')
    op.drop_index(op.f('ix_tool_host'), table_name='tool')
    op.drop_index(op.f('ix_tool_bundle_id'), table_name='tool')
    op.drop_table('tool')
    op.drop_index(op.f('ix_secret_provider'), table_name='secret')
    op.drop_index(op.f('ix_secret_owner'), table_name='secret')
    op.drop_index(op.f('ix_secret_org_id'), table_name='secret')
    op.drop_index(op.f('ix_secret_name'), table_name='secret')
    op.drop_index(op.f('ix_secret_bundle_id'), table_name='secret')
    op.drop_table('secret')
    op.drop_index(op.f('ix_idempotentcall_org_id'), table_name='idempotentcall')
    op.drop_index(op.f('ix_idempotentcall_membership_id'), table_name='idempotentcall')
    op.drop_index(op.f('ix_idempotentcall_key'), table_name='idempotentcall')
    op.drop_table('idempotentcall')
    op.drop_index(op.f('ix_denyrule_user_id'), table_name='denyrule')
    op.drop_index(op.f('ix_denyrule_project_id'), table_name='denyrule')
    op.drop_index(op.f('ix_denyrule_org_id'), table_name='denyrule')
    op.drop_table('denyrule')
    op.drop_index(op.f('ix_toolrequest_status'), table_name='toolrequest')
    op.drop_index(op.f('ix_toolrequest_source'), table_name='toolrequest')
    op.drop_index(op.f('ix_toolrequest_org_id'), table_name='toolrequest')
    op.drop_index(op.f('ix_toolrequest_created_at'), table_name='toolrequest')
    op.drop_index(op.f('ix_toolrequest_capability'), table_name='toolrequest')
    op.drop_table('toolrequest')
    op.drop_index(op.f('ix_tagspend_org_id'), table_name='tagspend')
    op.drop_index('ix_tagspend_org_dim_val_created', table_name='tagspend')
    op.drop_index(op.f('ix_tagspend_hold_id'), table_name='tagspend')
    op.drop_index(op.f('ix_tagspend_created_at'), table_name='tagspend')
    op.drop_table('tagspend')
    op.drop_index(op.f('ix_tagbudget_org_id'), table_name='tagbudget')
    op.drop_table('tagbudget')
    op.drop_index(op.f('ix_runrecord_user_email'), table_name='runrecord')
    op.drop_index(op.f('ix_runrecord_org_id'), table_name='runrecord')
    op.drop_index(op.f('ix_runrecord_bundle_name'), table_name='runrecord')
    op.drop_table('runrecord')
    op.drop_index('ix_referral_status_qualified', table_name='referral')
    op.drop_index(op.f('ix_referral_status'), table_name='referral')
    op.drop_index(op.f('ix_referral_referrer_user_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_referred_user_id'), table_name='referral')
    op.drop_index(op.f('ix_referral_created_at'), table_name='referral')
    op.drop_index(op.f('ix_referral_code'), table_name='referral')
    op.drop_index(op.f('ix_referral_card_fingerprint'), table_name='referral')
    op.drop_table('referral')
    op.drop_index(op.f('ix_project_slug'), table_name='project')
    op.drop_index(op.f('ix_project_org_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_pendingoauth_state'), table_name='pendingoauth')
    op.drop_index(op.f('ix_pendingoauth_owner'), table_name='pendingoauth')
    op.drop_index(op.f('ix_pendingoauth_org_id'), table_name='pendingoauth')
    op.drop_table('pendingoauth')
    op.drop_index(op.f('ix_oauthrefresh_user_id'), table_name='oauthrefresh')
    op.drop_index(op.f('ix_oauthrefresh_token_hash'), table_name='oauthrefresh')
    op.drop_index(op.f('ix_oauthrefresh_org_id'), table_name='oauthrefresh')
    op.drop_index(op.f('ix_oauthrefresh_family_id'), table_name='oauthrefresh')
    op.drop_index(op.f('ix_oauthrefresh_client_id'), table_name='oauthrefresh')
    op.drop_table('oauthrefresh')
    op.drop_index(op.f('ix_oauthgrant_current_org_id'), table_name='oauthgrant')
    op.drop_table('oauthgrant')
    op.drop_index(op.f('ix_oauthcode_user_id'), table_name='oauthcode')
    op.drop_index(op.f('ix_oauthcode_org_id'), table_name='oauthcode')
    op.drop_index(op.f('ix_oauthcode_code'), table_name='oauthcode')
    op.drop_index(op.f('ix_oauthcode_client_id'), table_name='oauthcode')
    op.drop_table('oauthcode')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_token_hash'), table_name='membership')
    op.drop_index(op.f('ix_membership_org_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_ledgerentry_org_id'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_kind'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_created_at'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_call_id'), table_name='ledgerentry')
    op.drop_index(op.f('ix_ledgerentry_block_id'), table_name='ledgerentry')
    op.drop_table('ledgerentry')
    op.drop_index(op.f('ix_invite_org_id'), table_name='invite')
    op.drop_index(op.f('ix_invite_email_token_hash'), table_name='invite')
    op.drop_index(op.f('ix_invite_email'), table_name='invite')
    op.drop_index(op.f('ix_invite_code_hash'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_hold_org_id'), table_name='hold')
    op.drop_index(op.f('ix_hold_created_at'), table_name='hold')
    op.drop_table('hold')
    op.drop_index(op.f('ix_creditblock_stripe_payment_intent'), table_name='creditblock')
    op.drop_index(op.f('ix_creditblock_org_id'), table_name='creditblock')
    op.drop_index(op.f('ix_creditblock_kind'), table_name='creditblock')
    op.drop_table('creditblock')
    op.drop_index(op.f('ix_capabilitypin_org_id'), table_name='capabilitypin')
    op.drop_index(op.f('ix_capabilitypin_capability'), table_name='capabilitypin')
    op.drop_table('capabilitypin')
    op.drop_index(op.f('ix_callrecord_user_email'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_tool_name'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_refused_by'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_provider'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_params_hash'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_org_id'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_endpoint_id'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_client'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_call_ref'), table_name='callrecord')
    op.drop_index(op.f('ix_callrecord_budget_val'), table_name='callrecord')
    op.drop_table('callrecord')
    op.drop_index(op.f('ix_bundle_owner'), table_name='bundle')
    op.drop_index(op.f('ix_bundle_org_id'), table_name='bundle')
    op.drop_index(op.f('ix_bundle_name'), table_name='bundle')
    op.drop_table('bundle')
    op.drop_index(op.f('ix_adconversion_uploaded_at'), table_name='adconversion')
    op.drop_index(op.f('ix_adconversion_org_id'), table_name='adconversion')
    op.drop_index(op.f('ix_adconversion_next_attempt_at'), table_name='adconversion')
    op.drop_index(op.f('ix_adconversion_failed_at'), table_name='adconversion')
    op.drop_table('adconversion')
    op.drop_index(op.f('ix_user_referral_code'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_searchmiss_source'), table_name='searchmiss')
    op.drop_index(op.f('ix_searchmiss_created_at'), table_name='searchmiss')
    op.drop_table('searchmiss')
    op.drop_index(op.f('ix_org_stripe_customer_id'), table_name='org')
    op.drop_index(op.f('ix_org_slug'), table_name='org')
    op.drop_table('org')
    op.drop_index(op.f('ix_oauthclient_client_id'), table_name='oauthclient')
    op.drop_table('oauthclient')
    op.drop_index(op.f('ix_ephemeral_expires_at'), table_name='ephemeral')
    op.drop_table('ephemeral')
    # ### end Alembic commands ###
