"""The plugins — shop windows whose contents must not drift from the product, or from each other.

Five of them now, generated by `scripts/build_plugin.py` from the one source `src/treg/web/skill.md`:

- **Codex/ChatGPT** (`plugin/`) — declares an MCP connector, so its skill checks for the five tools
  first and falls back to the CLI (the directory's upload path strips connector config).
- **Claude Code** (repo root `.claude-plugin/` + `skills/treg/`) — skills-only, written around the
  CLI. It lives at the repo root because that one path is what Claude Code's loader auto-discovers,
  what `npx skills add` resolves, and what `clawhub skill publish` takes.
- **Cursor** (repo root `.cursor-plugin/` + `plugins/treg/`) — declares an MCP connector pointing at
  the remote server, so its skill checks for the tools first like Codex. Unlike Claude Code, Cursor
  prescribes its own layout and the plugin root is NEVER the repo root.
- **DeepSeek Harness** (root `package.json` + `dsh/`) — no manifest at all: an npm package declaring
  `dsh.bundle`, whose patch mounts the skill and a treg MCP row that is disabled until there is a
  token. See docs/DSH-PLUGIN.md.
- **MiniMax** (`plugins/minimax/`) — skills-only again, because MiniMax rejects any credential in the
  package and gates authenticated MCP behind its App/Connector program. Its bootstrap has no
  `treg mcp install` step: that command cannot write a MiniMax config. See docs/MINIMAX-PLUGIN.md.

A generated file that nobody checks is a copy, and a copy rots — so the first test here is the one
that matters: regenerate, and fail if any checked-in copy differs.

The rest guard the manifests, because they are read by public directories rather than by us. A
broken path, an unsubstituted placeholder, or two listings that describe the product differently is
invisible locally and embarrassing in a store.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
PLUGIN = ROOT / "plugin"
MANIFEST = PLUGIN / ".codex-plugin" / "plugin.json"
SKILL = PLUGIN / "skills" / "treg" / "SKILL.md"

CLAUDE_PLUGIN = ROOT / ".claude-plugin"
CLAUDE_MANIFEST = CLAUDE_PLUGIN / "plugin.json"
CLAUDE_MARKETPLACE = CLAUDE_PLUGIN / "marketplace.json"
CLAUDE_SKILL = ROOT / "skills" / "treg" / "SKILL.md"

# Cursor prescribes its own layout (github.com/cursor/plugin-template): marketplace manifest at the
# repo root, each plugin under plugins/<name>/ with its own .cursor-plugin/plugin.json. The plugin
# root is NEVER the repo root here — that is the difference from Claude Code that is easy to get
# wrong, and `source` pointing at the wrong place installs an empty plugin.
CURSOR_MARKETPLACE = ROOT / ".cursor-plugin" / "marketplace.json"
CURSOR_PLUGIN_DIR = ROOT / "plugins" / "treg"
CURSOR_MANIFEST = CURSOR_PLUGIN_DIR / ".cursor-plugin" / "plugin.json"
CURSOR_SKILL = CURSOR_PLUGIN_DIR / "skills" / "treg" / "SKILL.md"

# DeepSeek Harness has no plugin manifest at all: it installs an npm package whose `package.json`
# declares `dsh.bundle`, pointing at a config layer. So the "manifest" here is package.json, and the
# thing that decides what a user gets is the patch — hence the extra tests at the bottom.
DSH_MANIFEST = ROOT / "package.json"
DSH_PATCH = ROOT / "dsh" / "cordis.patch.yml"
DSH_ENTRY = ROOT / "dsh" / "index.js"
DSH_SKILL = ROOT / "dsh" / "skills" / "treg" / "SKILL.md"

# MiniMax (MiniMax Code + MiniMax Agent) prescribes `.minimax-plugin/plugin.json` at the plugin root
# and rejects any package holding a credential, so this one is skills-only from its own root
# `plugins/minimax/`, submitted as a GitHub subdirectory or a wrapper-free ZIP. See docs/MINIMAX-PLUGIN.md.
MINIMAX_PLUGIN_DIR = ROOT / "plugins" / "minimax"
MINIMAX_MANIFEST = MINIMAX_PLUGIN_DIR / ".minimax-plugin" / "plugin.json"
MINIMAX_SKILL = MINIMAX_PLUGIN_DIR / "skills" / "treg" / "SKILL.md"

# Every generated SKILL.md, and every manifest a public directory reads. Tests that apply to the
# product as a whole (version, positioning, no-routing) parametrise over these rather than being
# written against whichever plugin happened to exist first.
ALL_SKILLS = {"codex": SKILL, "claude": CLAUDE_SKILL, "cursor": CURSOR_SKILL, "dsh": DSH_SKILL,
              "minimax": MINIMAX_SKILL}
ALL_MANIFESTS = {"codex": MANIFEST, "claude": CLAUDE_MANIFEST, "cursor": CURSOR_MANIFEST,
                 "dsh": DSH_MANIFEST, "minimax": MINIMAX_MANIFEST}

# The one line that positions the product. It is the same sentence `llms.txt` opens with, and it is
# hand-maintained in three places across two stores — which is exactly the shape of thing that
# drifts, so it is pinned rather than trusted.
POSITIONING = ("OpenRouter for tools - 2,896 agent-friendly tools, "
               "pay for the usage, not subscription")


def package_version() -> str:
    pyproject = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    return next(l.split('"')[1] for l in pyproject.splitlines() if l.startswith("version = "))


def frontmatter(path: Path) -> dict:
    """The skill's YAML frontmatter as a flat dict. Deliberately a 6-line parser and not a yaml
    import: the CLI-path modules must not gain a heavy dependency, and the frontmatter here is
    three scalar keys."""
    text = path.read_text(encoding="utf-8")
    assert text.startswith("---\n"), f"{path} does not open with frontmatter"
    block = text.split("---", 2)[1]
    out = {}
    for line in block.strip().splitlines():
        key, _, value = line.partition(":")
        out[key.strip()] = value.strip()
    return out


@pytest.fixture(scope="module")
def manifest() -> dict:
    return json.loads(MANIFEST.read_text(encoding="utf-8"))


def test_the_plugin_skill_is_not_stale():
    """`build_plugin.py --check` is the whole point: the served skill.md is the ONE source, and this
    is what notices when the plugin falls behind it."""
    r = subprocess.run([sys.executable, str(ROOT / "scripts" / "build_plugin.py"), "--check"],
                       capture_output=True, text=True)
    assert r.returncode == 0, (
        f"plugin SKILL.md is stale — regenerate with `python3 scripts/build_plugin.py`\n"
        f"{r.stdout}{r.stderr}")


@pytest.mark.parametrize("variant", sorted(ALL_SKILLS))
def test_no_unsubstituted_placeholder_reaches_the_plugin(variant):
    """`{BASE}` is substituted per-request by the SERVER. Nothing substitutes it inside an installed
    plugin, so shipping the literal would break every URL in the most-read page of the product."""
    text = ALL_SKILLS[variant].read_text(encoding="utf-8")
    assert "{BASE}" not in text
    assert "https://treg.to/install.sh" in text


def test_the_skill_maps_itself_onto_the_MCP_TOOLS(manifest):
    """The served skill is written around the `treg` command line — every other install path reaches
    treg that way. A plugin user has no terminal: they have the connector's tools. Without the
    mapping, the first run is an agent trying to run a shell command that does not exist."""
    text = SKILL.read_text(encoding="utf-8")
    for tool in ("catalog_search", "catalog_get", "call", "balance", "my_tools"):
        assert tool in text, f"the skill never mentions the {tool} tool"
    assert "TREG_TOKEN" in text            # what to do when the connector has no token yet
    assert manifest["mcpServers"] == "./.mcp.json"


def test_the_connector_points_at_production_over_https():
    """The listing is public. A plugin shipped pointing at a dev box or over http would work for
    exactly one person, and reviewers test from their own machines."""
    import json as _json
    mcp = _json.loads((PLUGIN / ".mcp.json").read_text(encoding="utf-8"))
    assert set(mcp) == {"treg"}
    url = mcp["treg"]["url"]
    assert url.startswith("https://"), url
    assert "ngrok" not in url and "localhost" not in url and "127.0.0.1" not in url
    assert mcp["treg"]["bearer_token_env_var"] == "TREG_TOKEN"


def test_category_and_capabilities_match_what_real_plugins_use(manifest):
    """These were guesses until I read OpenAI's own installed manifests under
    `~/.codex/plugins/cache/`: github is `Developer Tools` + ["Interactive", "Write"], gmail is
    `Communication`, openai-templates is `Productivity`. The published docs list neither set of
    allowed values, so the shipped plugins are the only real reference — and a store listing filed
    under an invented category is not a thing you get to quietly fix later."""
    iface = manifest["interface"]
    assert iface["category"] in {"Developer Tools", "Productivity", "Communication"}
    assert set(iface["capabilities"]) <= {"Interactive", "Write", "Read"}


def test_manifest_declares_what_the_directory_reads(manifest):
    for field in ("name", "version", "description", "skills", "interface"):
        assert manifest.get(field), f"plugin.json is missing `{field}`"
    iface = manifest["interface"]
    for field in ("displayName", "shortDescription", "longDescription", "category",
                  "composerIcon", "logo"):
        assert iface.get(field), f"plugin.json interface is missing `{field}`"


def test_at_most_three_default_prompts(manifest):
    """OpenAI's upload form rejects the bundle outright: "`interface.defaultPrompt` must contain at
    most three prompts." Nothing local surfaced that — it cost an upload round-trip to find, which is
    exactly the kind of limit worth pinning rather than rediscovering."""
    prompts = manifest["interface"]["defaultPrompt"]
    assert 1 <= len(prompts) <= 3, f"the directory allows at most 3 default prompts, found {len(prompts)}"


def test_every_declared_path_exists(manifest):
    """A path that resolves on the author's machine and nowhere else is the classic packaging bug."""
    paths = [manifest["skills"], manifest["interface"]["composerIcon"], manifest["interface"]["logo"]]
    paths += manifest["interface"].get("screenshots", [])
    for rel in paths:
        assert rel.startswith("./"), f"{rel} must be relative to the plugin root"
        assert (PLUGIN / rel[2:]).exists(), f"plugin.json points at {rel}, which does not exist"


@pytest.mark.parametrize("variant", sorted(ALL_MANIFESTS))
def test_plugin_version_tracks_the_package(variant):
    """One product, one version. A listing that claims 0.1.0 while the CLI is 0.7.0 is a support
    question waiting to happen."""
    manifest = json.loads(ALL_MANIFESTS[variant].read_text(encoding="utf-8"))
    assert manifest["version"] == package_version()


@pytest.mark.parametrize("variant", sorted(ALL_MANIFESTS))
def test_the_listing_does_not_promise_routing(variant):
    """The charter's standing rule: treg COMPARES providers, it does not route or fail over. The
    landing page already had to be corrected for this once — a store listing is harder to correct."""
    blob = ALL_MANIFESTS[variant].read_text(encoding="utf-8").lower()
    for claim in ("routes for you", "automatic failover", "fails over", "picks the best provider"):
        assert claim not in blob, f"listing copy claims {claim!r}, which treg does not do"


# --------------------------------------------------------------------------------------------
# The Claude Code plugin — skills-only, and its own marketplace.
# --------------------------------------------------------------------------------------------

def test_the_claude_skill_carries_the_version_clawhub_requires():
    """ClawHub refuses a skill whose frontmatter lacks a semver `version`, and requires `name` to
    match the parent directory. Claude Code ignores the extra key, which is the whole reason one
    generated file can serve both — but only for as long as the stamp keeps happening, and a release
    bump is exactly when it would quietly stop."""
    fm = frontmatter(CLAUDE_SKILL)
    assert fm["name"] == "treg" == CLAUDE_SKILL.parent.name
    assert fm["version"] == package_version()
    assert fm.get("description"), "the description is what drives discovery in every registry"


def test_the_claude_plugin_declares_no_connector_in_its_manifest():
    """Skills-only is a property of the MANIFEST, not of the end state — the skill still wires up the
    MCP tools at first run (see the ordering test below). The distinction is the whole design.

    Anything declared here is registered at INSTALL time, before any human has signed in, so a
    declared MCP server means five always-on tools that 401 on every call. Leaving it out is what
    makes `/plugin install` a zero-config action and keeps this off the connector-review track."""
    manifest = json.loads(CLAUDE_MANIFEST.read_text(encoding="utf-8"))
    assert "mcpServers" not in manifest
    assert not (ROOT / ".mcp.json").exists(), "a root .mcp.json would be picked up by the plugin"


def test_the_claude_bootstrap_sets_up_cli_login_and_mcp_in_order():
    """The plugin is skills-only at the MANIFEST level so it installs with no token and no config —
    but the intended first run ends with the CLI, the skill AND the MCP tools all in place. The skill
    is what wires the last two up, because only it runs after the human is present to sign in.

    Order is load-bearing and not merely stylistic: `cmd_mcp_install` (cli.py) reads the token from
    config and `sys.exit`s before writing anything when there is none. Run `treg mcp install` ahead
    of `treg login` and it does nothing at all — silently enough that an agent would move on assuming
    the tools exist."""
    text = CLAUDE_SKILL.read_text(encoding="utf-8")
    head = text.split("---", 3)[2]          # the prepended bootstrap, before the skill's own body
    steps = ["install.sh", "treg login", "treg mcp install"]
    positions = [head.find(s) for s in steps]
    assert all(p != -1 for p in positions), f"the bootstrap is missing one of {steps}"
    assert positions == sorted(positions), (
        "the bootstrap must present install -> login -> mcp install IN THAT ORDER; "
        "`treg mcp install` exits without writing if it runs before there is a token")
    assert "restart" in head.lower(), (
        "registering an MCP server needs an agent restart to take effect — an agent that does not "
        "say so leaves the human waiting for tools that will not appear this session")


def test_the_marketplace_resolves_to_a_real_plugin():
    """`source` is resolved by Claude Code on the user's machine, not here. A source that points at
    a directory with no `skills/` installs an empty plugin — silently, which is the failure mode
    CLAUDE.md warns about for exactly this kind of markup."""
    market = json.loads(CLAUDE_MARKETPLACE.read_text(encoding="utf-8"))
    manifest = json.loads(CLAUDE_MANIFEST.read_text(encoding="utf-8"))
    assert len(market["plugins"]) == 1
    entry = market["plugins"][0]
    assert entry["name"] == manifest["name"]
    root = (CLAUDE_PLUGIN.parent / entry["source"]).resolve()
    assert (root / "skills" / "treg" / "SKILL.md").exists(), (
        f"marketplace source {entry['source']!r} resolves to {root}, which ships no treg skill")
    # `source: "./"` makes the plugin root the REPO root, so anything Claude Code auto-discovers
    # there ships to users. Only `skills/` is intended.
    for stray in ("commands", "agents", "hooks"):
        assert not (root / stray).is_dir(), (
            f"a root `{stray}/` directory would be published as part of the plugin")


def test_one_product_one_sentence():
    """The positioning is hand-maintained across two stores, and two listings describing the same
    product differently is drift nobody notices until a user reads both."""
    claude = json.loads(CLAUDE_MANIFEST.read_text(encoding="utf-8"))
    market = json.loads(CLAUDE_MARKETPLACE.read_text(encoding="utf-8"))
    assert claude["description"] == POSITIONING
    assert market["description"] == POSITIONING


def test_the_codex_subtitle_fits_the_field():
    """Codex renders `shortDescription` as the listing SUBTITLE, and the upload form rejects
    anything over 30 characters — so it cannot carry the full positioning sentence the way the
    Claude manifest's `description` does. It keeps the front half, which is the half that
    identifies the product."""
    subtitle = json.loads(MANIFEST.read_text(encoding="utf-8"))["interface"]["shortDescription"]
    assert len(subtitle) <= 30, f"subtitle is {len(subtitle)} chars, the field allows 30"
    assert subtitle.split()[0] in POSITIONING


def test_the_listings_agree_on_the_licence():
    """`LICENSE` is Apache-2.0 plus a hosted-service restriction. The Codex manifest claimed MIT for
    a while, which is a licence the project has never been under — and a store listing is where a
    wrong licence does actual damage."""
    for variant, path in ALL_MANIFESTS.items():
        if variant == "minimax":
            continue  # its schema has no licence field, and unknown keys risk their validator
        manifest = json.loads(path.read_text(encoding="utf-8"))
        assert manifest["license"] == "Apache-2.0", f"{path.name} misstates the licence"


def test_the_cursor_layout_matches_cursors_template():
    """Cursor prescribes the shape (github.com/cursor/plugin-template): marketplace manifest at the
    repo root, plugin under plugins/<name>/ with its own .cursor-plugin/plugin.json, and `source`
    the relative path to that folder. Unlike Claude Code, the plugin root is never the repo root —
    get that wrong and the listing installs nothing. Their own validator agrees with this test."""
    market = json.loads(CURSOR_MARKETPLACE.read_text(encoding="utf-8"))
    manifest = json.loads(CURSOR_MANIFEST.read_text(encoding="utf-8"))

    assert len(market["plugins"]) == 1
    entry = market["plugins"][0]
    assert entry["name"] == manifest["name"] == "treg"
    assert entry["name"] == entry["name"].lower() and " " not in entry["name"]  # kebab-case
    assert entry["source"] == f"./plugins/{entry['name']}", (
        "`source` must be the relative path to the plugin folder, and match the folder name")

    root = (ROOT / entry["source"]).resolve()
    assert root == CURSOR_PLUGIN_DIR.resolve()
    assert (root / ".cursor-plugin" / "plugin.json").exists()
    assert (root / "skills" / "treg" / "SKILL.md").exists()

    # Cursor's marketplace schema differs from Claude's: a metadata{} block rather than a top-level
    # description, and no $schema. Do not "fix" one to look like the other.
    assert market["metadata"]["description"] and market["metadata"]["version"]
    assert "description" not in market

    logo = manifest["logo"]
    assert not logo.startswith("./"), "the template writes `assets/logo.svg`, not `./assets/...`"
    assert (root / logo).exists(), f"plugin.json points at {logo}, which does not exist"


def test_the_cursor_plugin_ships_mcp_alongside_the_skill():
    """Cursor now ships MCP tools alongside the skill, so users don't need `treg mcp install`.
    The manifest declares `mcpServers` pointing at a config file, and that file contains the
    remote server entry with Cursor's env variable syntax for the token."""
    manifest = json.loads(CURSOR_MANIFEST.read_text(encoding="utf-8"))
    assert manifest["mcpServers"] == "./mcp.json", "the manifest must point to the MCP config"
    assert manifest["skills"] == "./skills/", "the manifest must still ship the skill"

    mcp_config = json.loads((CURSOR_PLUGIN_DIR / "mcp.json").read_text(encoding="utf-8"))
    assert "mcpServers" in mcp_config, "Cursor's MCP config uses the { mcpServers: {...} } wrapper"
    assert "treg" in mcp_config["mcpServers"]
    server = mcp_config["mcpServers"]["treg"]
    assert server["url"] == "https://treg.to/mcp/", "the MCP URL must be the production endpoint"
    assert "${env:TREG_TOKEN}" in json.dumps(server), (
        "auth must use Cursor's env variable syntax, not a hardcoded token")
    assert "localhost" not in server["url"] and "127.0.0.1" not in server["url"]


def test_the_cursor_bootstrap_checks_for_tools_first_and_maps_them():
    """Like the Codex plugin, Cursor now ships MCP, so its skill checks for the tools first and
    maps the page onto them. Unlike Claude Code, it does NOT tell the agent to run `treg mcp
    install` — the plugin already ships the config."""
    text = CURSOR_SKILL.read_text(encoding="utf-8")
    head = text.split("---", 3)[2]  # the prepended bootstrap, before the skill's own body
    for tool in ("catalog_search", "catalog_get", "call", "balance", "my_tools"):
        assert tool in head, f"the bootstrap never mentions the {tool} tool"
    assert "TREG_TOKEN" in head, "the bootstrap must explain how to set the token"
    assert "treg mcp install" not in head, (
        "the Cursor plugin ships MCP — `treg mcp install` would duplicate what the plugin provides")


# --------------------------------------------------------------------------------------------
# The DeepSeek Harness bundle — an npm package, not a manifest, and the only surface that ships
# the connector alongside the CLI path.
# --------------------------------------------------------------------------------------------

def test_the_dsh_bundle_declares_the_patch_dsh_reads():
    """dsh does not read a `plugin.json`. It installs a package whose `package.json` declares
    `dsh.bundle.patch`, and a package without that declaration installs as a plain dependency that
    activates NO layer — `dsh plugin` prints a warning and the user gets nothing, silently enough to
    look like it worked."""
    manifest = json.loads(DSH_MANIFEST.read_text(encoding="utf-8"))
    assert manifest["dsh"]["bundle"]["patch"] == "./dsh/cordis.patch.yml"
    assert (ROOT / manifest["dsh"]["bundle"]["patch"][2:]).exists()
    assert manifest["type"] == "module", "the entry is plain ESM; CommonJS would fail to load it"
    assert (ROOT / manifest["main"]).exists(), f"`main` points at {manifest['main']}, which is missing"
    for rel in manifest["files"]:
        assert (ROOT / rel).exists(), f"`files` ships {rel}, which does not exist"


def test_the_dsh_bundle_needs_no_build_step():
    """`dsh plugin add github:...` fetches SOURCES, not build output. A package with a `prepare`
    script makes pnpm refuse the install until the user allowlists the build in their profile's
    pnpm-workspace.yaml — i.e. the documented install command fails for everyone on first run. The
    entry is therefore hand-written ESM, and depends on nothing."""
    manifest = json.loads(DSH_MANIFEST.read_text(encoding="utf-8"))
    assert "prepare" not in manifest.get("scripts", {})
    assert not manifest.get("dependencies"), (
        "an out-of-tree bundle that depends on an in-box @deepseek-ai package installs a SECOND "
        "copy of it, which then drifts from the host's")


def test_the_dsh_mcp_row_is_disabled_until_there_is_a_token():
    """The same reasoning as the Claude manifest declaring no connector: a treg MCP server
    registered before anyone has signed in is five always-on tools that 401 on every call. dsh can
    express the better version — the row exists but is disabled until `TREG_TOKEN` is in the
    environment — so a token-holder gets the tools at boot and everyone else gets a clean install."""
    patch = DSH_PATCH.read_text(encoding="utf-8")
    assert "@deepseek-ai/dsh-mcp-client" in patch
    assert "disabled: !!js (process.env.TREG_TOKEN ?? '') === ''" in patch, (
        "the MCP row must stay disabled until TREG_TOKEN exists")
    # Found by running the real dsh against this file: an expression that STARTS with `!` makes the
    # YAML parser read a second tag property, and the whole profile fails to load with
    # "duplication of a tag property" — not just this row. So `!process.env.TREG_TOKEN` is banned.
    assert "!!js !" not in patch, "a `!!js` expression must not begin with `!`"
    assert "https://treg.to/mcp/" in patch
    assert "localhost" not in patch and "127.0.0.1" not in patch


def test_the_dsh_bootstrap_names_the_namespaced_tools_and_avoids_mcp_install():
    """Two ways a dsh user gets stranded. The tools are namespaced (`mcp__treg__call`, not `call`),
    so a page naming the bare tool names has the agent looking for something that is not there. And
    `treg mcp install` writes Claude Code / Cursor / opencode configs — never a dsh profile — so an
    agent that reaches for it produces no tools and no error either."""
    head = DSH_SKILL.read_text(encoding="utf-8").split("---", 2)[2]
    for tool in ("mcp__treg__catalog_search", "mcp__treg__call", "mcp__treg__balance"):
        assert tool in head, f"the bootstrap never names {tool}"
    assert "TREG_TOKEN" in head
    assert "restart" in head.lower(), (
        "the row is evaluated at boot, so a token exported afterwards needs a restart to take effect")
    assert "not** run `treg mcp install`" in head or "not run `treg mcp install`" in head, (
        "the bootstrap must steer away from `treg mcp install`, which cannot write a dsh profile")


# --------------------------------------------------------------------------------------------
# The MiniMax plugin — skills-only, validated against the rules in docs/MINIMAX-PLUGIN.md.
# --------------------------------------------------------------------------------------------

def test_the_minimax_package_passes_the_marketplace_validator():
    """`scripts/minimax_plugin.py --check` is the same set of rules MiniMax's intake runs (manifest
    shape, referenced files exist, ASCII paths, no symlinks/scripts/binaries, no secrets). Fail here
    rather than in their queue."""
    r = subprocess.run([sys.executable, str(ROOT / "scripts" / "minimax_plugin.py"), "--check"],
                       capture_output=True, text=True)
    assert r.returncode == 0, r.stdout + r.stderr


def test_the_minimax_plugin_is_skills_only_and_tells_the_agent_not_to_mcp_install():
    """Two things MiniMax makes non-negotiable. The package may hold no credential, and treg's MCP
    is bearer-authed — so `mcpServers` stays empty. And `treg mcp install` writes configs for other
    agents only; a bootstrap that recommended it would be a silent no-op on MiniMax Code."""
    manifest = json.loads(MINIMAX_MANIFEST.read_text(encoding="utf-8"))
    assert manifest["mcpServers"] == [] and manifest["apps"] == []
    assert manifest["skills"] == ["skills/treg/SKILL.md"]
    assert not list(MINIMAX_PLUGIN_DIR.glob("*.mcp.json"))
    body = MINIMAX_SKILL.read_text(encoding="utf-8")
    assert "Do **not** run `treg mcp install`" in body
    assert frontmatter(MINIMAX_SKILL)["name"] == "treg" == MINIMAX_SKILL.parent.name
