"""Private, content-addressed object storage. SDK imports stay inside the server factory."""
from contextlib import asynccontextmanager
from dataclasses import dataclass
import hashlib
import re
from typing import Protocol


@dataclass(frozen=True)
class ObjectInfo:
    content_hash: str
    size: int


R2_ENDPOINT_RE = re.compile(r"https://[0-9a-f]{32}(?:\.(?:eu|fedramp))?\.r2\.cloudflarestorage\.com")


class ObjectStore(Protocol):
    async def put(self, body: bytes, *, content_hash: str | None = None) -> ObjectInfo: ...
    async def get(self, content_hash: str) -> bytes | None: ...
    async def head(self, content_hash: str) -> ObjectInfo | None: ...


def _key(content_hash: str) -> str:
    # Only hashes generated by treg or read from its archive are accepted, never a path or URL.
    if not re.fullmatch(r"[0-9a-f]{64}", content_hash):
        raise ValueError("invalid archive content hash")
    return content_hash


class ObjectStoreError(ValueError):
    """A bounded, credential-free reason at the SDK boundary."""
    def __init__(self, reason: str):
        self.reason = reason
        super().__init__(reason)


class R2ObjectStore:
    def __init__(self, client, max_body_bytes: int, *, auth_errors=()):
        self._client, self._max_bytes = client, max_body_bytes
        self._auth_errors = (PermissionError, *auth_errors)

    async def put(self, body: bytes, *, content_hash: str | None = None) -> ObjectInfo:
        if len(body) > self._max_bytes:
            raise ValueError("archive body too large")
        key = _key(content_hash) if content_hash is not None else hashlib.sha256(body).hexdigest()
        try:
            await self._client.put_async(
                key, body, attributes={"Content-Type": "application/octet-stream"}, use_multipart=False)
        except Exception as exc:
            raise self._failure(exc) from None
        return ObjectInfo(key, len(body))

    async def head(self, content_hash: str) -> ObjectInfo | None:
        key = _key(content_hash)
        try:
            meta = await self._client.head_async(key)
        except FileNotFoundError:
            return None
        return ObjectInfo(key, int(meta["size"]))

    async def get(self, content_hash: str) -> bytes | None:
        key = _key(content_hash)
        try:
            result = await self._client.get_async(key)
            if result.meta["size"] > self._max_bytes:
                raise ObjectStoreError("too_large")
            body = bytes(await result.bytes_async())
            if len(body) > self._max_bytes:
                raise ObjectStoreError("too_large")
            if hashlib.sha256(body).hexdigest() != key:
                raise ObjectStoreError("hash_mismatch")
            return body
        except FileNotFoundError:
            return None
        except ObjectStoreError:
            raise
        except Exception as exc:
            raise self._failure(exc) from None

    def _failure(self, exc):
        if isinstance(exc, self._auth_errors):
            return ObjectStoreError("permission_denied")
        if isinstance(exc, FileNotFoundError):
            return ObjectStoreError("not_found")
        if isinstance(exc, TimeoutError):
            return ObjectStoreError("timeout")
        return ObjectStoreError("store_error")


@asynccontextmanager
async def open_r2(settings):
    from obstore.exceptions import PermissionDeniedError, UnauthenticatedError
    from obstore.store import S3Store

    transport_timeout = max(settings.archive_r2_timeout_s, settings.archive_r2_read_timeout_s)
    client = S3Store(
        settings.archive_object_store_bucket,
        config={
            "endpoint": settings.archive_object_store_endpoint, "region": "auto",
            "access_key_id": settings.archive_object_store_access_key_id,
            "secret_access_key": settings.archive_object_store_secret_access_key,
            "checksum_algorithm": "SHA256",
        },
        client_options={"timeout": f"{transport_timeout}s",
                        "connect_timeout": f"{transport_timeout}s"},
        retry_config={"max_retries": 0})
    # One shared Rust HTTP pool for the lifespan. S3Store has no explicit close operation;
    # dropping the store after archive drains releases its client and pool.
    yield R2ObjectStore(client, settings.archive_max_body_bytes,
                        auth_errors=(PermissionDeniedError, UnauthenticatedError))
